add sqlite persistence test to buildkite (#6796)

diff --git a/.buildkite/pipeline-master.yml b/.buildkite/pipeline-master.yml
--- a/.buildkite/pipeline-master.yml
+++ b/.buildkite/pipeline-master.yml
@@ -2,22 +2,22 @@
 container:
   kubernetes: &kubernetes
     sidecars:
-    - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
-      volumeMounts:
-        - mountPath: /var/run/
-          name: docker-sock
-      securityContext:
-        privileged: true
-        allowPrivilegeEscalation: true
+      - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
+        volumeMounts:
+          - mountPath: /var/run/
+            name: docker-sock
+        securityContext:
+          privileged: true
+          allowPrivilegeEscalation: true
     mirrorVolumeMounts: true # CRITICAL: this must be at the same indentation level as sidecars
     podSpec: &podSpec
       containers:
         - &commandContainer
           image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
           command:
-          - |-
-            echo "Command step was not overridden."
-            exit 1
+            - |-
+              echo "Command step was not overridden."
+              exit 1
           volumeMounts:
             - mountPath: /var/run/
               name: docker-sock
@@ -26,8 +26,8 @@ container:
               cpu: 7500m
               memory: 30G
       volumes:
-      - name: docker-sock
-        emptyDir: {}
+        - name: docker-sock
+          emptyDir: { }
 
 agents:
   queue: buildkite-gcp
@@ -61,18 +61,18 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  # ensure that we are not rebuilding binaries and not regenerating code
-                  make .just-build
-                  # make install-schema is needed for a server startup test. See main_test.go
-                  CASSANDRA_HOST=cassandra make install-schema && make cover_profile
-                  ./scripts/buildkite/gen_coverage_metadata.sh .build/coverage/metadata.txt
+                  - |-
+                    # ensure that we are not rebuilding binaries and not regenerating code
+                    make .just-build
+                    # make install-schema is needed for a server startup test. See main_test.go
+                    CASSANDRA_HOST=cassandra make install-schema && make cover_profile
+                    ./scripts/buildkite/gen_coverage_metadata.sh .build/coverage/metadata.txt
       - docker-compose#v3.0.0:
           run: unit-test
           config: docker/buildkite/docker-compose.yml
 
   - label: ":golangci-lint: validate code is clean"
-    artifact_paths: []
+    artifact_paths: [ ]
     retry:
       automatic:
         limit: 1
@@ -84,8 +84,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  ./scripts/buildkite/golint.sh
+                  - |-
+                    ./scripts/buildkite/golint.sh
       - docker-compose#v3.0.0:
           run: coverage-report
           config: docker/buildkite/docker-compose.yml
@@ -104,8 +104,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_integration_profile
+                  - |-
+                    make cover_integration_profile
       - docker-compose#v3.0.0:
           run: integration-test-cassandra
           config: docker/buildkite/docker-compose.yml
@@ -124,8 +124,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_integration_profile
+                  - |-
+                    make cover_integration_profile
       - docker-compose#v3.0.0:
           run: integration-test-cassandra
           config: docker/buildkite/docker-compose-es7.yml
@@ -167,8 +167,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_integration_profile
+                  - |-
+                    make cover_integration_profile
       - docker-compose#v3.0.0:
           run: integration-test-cassandra
           config: docker/buildkite/docker-compose-opensearch2.yml
@@ -187,8 +187,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_ndc_profile
+                  - |-
+                    make cover_ndc_profile
       - docker-compose#v3.0.0:
           run: integration-test-ndc-cassandra
           config: docker/buildkite/docker-compose.yml
@@ -207,8 +207,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_integration_profile
+                  - |-
+                    make cover_integration_profile
       - docker-compose#v3.0.0:
           run: integration-test-mysql
           config: docker/buildkite/docker-compose.yml
@@ -227,8 +227,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_ndc_profile
+                  - |-
+                    make cover_ndc_profile
       - docker-compose#v3.0.0:
           run: integration-test-ndc-mysql
           config: docker/buildkite/docker-compose.yml
@@ -247,10 +247,34 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_integration_profile
+                  - |-
+                    make cover_integration_profile
       - docker-compose#v3.0.0:
           run: integration-test-postgres
+          config: docker/buildkite/docker-compose.yml
+
+  - label: ":golang: integration test with sqlite"
+    artifact_paths:
+      - ".build/coverage/*.out"
+    # sqlite persistence storage is still in development
+    # so persistence tests should not fail the build
+    # but we still want to run them
+    soft_fail: true
+    retry:
+      automatic:
+        limit: 1
+    plugins:
+      - kubernetes:
+          <<: *kubernetes
+          podSpec:
+            <<: *podSpec
+            containers:
+              - <<: *commandContainer
+                command:
+                  - |-
+                    make cover_integration_profile
+      - docker-compose#v3.0.0:
+          run: integration-test-sqlite
           config: docker/buildkite/docker-compose.yml
 
   - label: ":golang: integration ndc test with postgres"
@@ -267,8 +291,8 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  make cover_ndc_profile
+                  - |-
+                    make cover_ndc_profile
       - docker-compose#v3.0.0:
           run: integration-test-ndc-postgres
           config: docker/buildkite/docker-compose.yml
@@ -285,10 +309,10 @@ steps:
             containers:
               - <<: *commandContainer
                 command:
-                - |-
-                  # ensure that we are not rebuilding binaries and not regenerating code
-                  make .just-build
-                  go test -timeout 60s -run ^TestAsyncWFIntegrationSuite -tags asyncwfintegration -count 1 -v github.com/uber/cadence/host
+                  - |-
+                    # ensure that we are not rebuilding binaries and not regenerating code
+                    make .just-build
+                    go test -timeout 60s -run ^TestAsyncWFIntegrationSuite -tags asyncwfintegration -count 1 -v github.com/uber/cadence/host
       - docker-compose#v3.0.0:
           run: integration-test-async-wf
           config: docker/buildkite/docker-compose.yml
